### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by lenyabloko** [mgckind/keepcli#3]
Hi there,
I was trying to follow the instructions to install, but got some errors

$ pip install keepcli
Collecting keepcli
  Downloading https://files.pythonhosted.org/packages/25/c1/250513dada049a8680568b61c9afd3c384d8ed93a7c41e0cddf7fa8d571a/keepcli-1.0.1-py2.py3-none-any.whl
Collecting gkeepapi==0.10.9 (from keepcli)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/b8/e3/77631ffd1449e2ed6ff048c701ff62d2a18114d15307efb071bb1eccbca4/gkeepapi-0.10.9-py2.py3-none-any.whl
Collecting termcolor==1.1.0 (from keepcli)
  Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Requirement already satisfied: PyYAML==3.13 in ./anaconda3/lib/python3.6/site-packages (from keepcli)
Collecting setuptools==34.4.0 (from keepcli)
  Downloading https://files.pythonhosted.org/packages/4f/45/4ff49ef85e3bda6e63eefeae4d42642de0c58b63acabf01cbf3512b851f6/se
tuptools-34.4.0-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 399kB 2.5MB/s
Collecting gpsoauth>=0.4.1 (from gkeepapi==0.10.9->keepcli)
  Cache entry deserialization failed, entry ignored
Exception:
Traceback (most recent call last):
  File "/home/lenyabloko/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/lenyabloko/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/lenyabloko/anaconda3/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/lenyabloko/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/lenyabloko/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/lenyabloko/anaconda3/lib/python3.6/site-packages/pip/download.py", line 809, in unpack_url

**Comment by mgckind** [comment]
Hi, were you able to install gkeepapi by itself? that might help to track down the problem and then install using `pip install keepcli  --no-deps`

**Comment by lenyabloko** [comment]
Hi, yes - without deps no problem.

**Comment by mgckind** [comment]
good to hear, thanks
