### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by 3mru** [mgckind/keepcli#4]
Whenever i try to login in i get this error

Traceback (most recent call last):                 
  File "/usr/local/bin/keepcli", line 3, in <module>                                                   
    keep.cli()                                     
  File "/usr/local/lib/python3.7/site-packages/keepcli/keep.py", line 1054, in cli                     
    GKeep(auth_file=auth_file, conf_file=conf_file,
offline=offline).cmdloop()                         
  File "/usr/local/lib/python3.7/site-packages/keepcli/keep.py", line 148, in __init__                 
    self.connect = self.keep.login(conn['user'], conn['passwd'])                                       
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 404, in login               
    self.load(auth)                                
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 418, in load                
    self.sync(True)                                
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 645, in sync                
    self._parseNodes(changes['nodes'])             
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 672, in _parseNodes         
    node = _node.from_json(raw_node)               
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/node.py", line 1450, in from_json              
    node.load(raw)                                 
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/node.py", line 1027, in load                   
    self._title = raw['title']                     
KeyError: 'title'

**Comment by dmd** [comment]
I'm getting this same error. Can you help?

**Comment by dmd** [comment]
Here's raw:

```
-> self._title = raw['title']
(Pdb) raw
{'kind': 'notes#node', 'id': '1556409187104.283936.3810743527', 'serverId': '1OsAwrAtnQX2rdu2OCVy7K6ngYUfDHAe8mYWcym-02pBQ7QCZwTE8dMO03nPIlShQkNNbXDAS', 'parentId': 'root', 'type': 'NOTE', 'timestamps': {'kind': 'notes#timestamps', 'created': '2019-04-27T23:53:09.346Z', 'updated': '2019-04-27T23:53:25.415Z', 'trashed': '2019-04-27T23:53:25.415Z', 'userEdited': '2019-04-27T23:53:16.351Z'}, 'nodeSettings': {'newListItemPlacement': 'BOTTOM', 'checkedListItemsPolicy': 'GRAVEYARD', 'graveyardState': 'EXPANDED'}, 'isArchived': False, 'isPinned': False, 'sortValue': '504365056', 'annotationsGroup': {'kind': 'notes#annotationsGroup'}, 'lastModifierEmail': 'ddruckerccn@gmail.com', 'moved': '1'}
```

**Comment by mgckind** [comment]
Hi @dmd, 
I haven't been able to reproduce the problem myself EXCEPT when I had a bad formatted note in Google Keep but don't remember exactly what and I haven't revisit the problem.

Since you posted the debugger output, can you back up that Note, delete it and try again? Not every option or every format is supported unfortunately and can't remember exactly what failed last time I saw this error

**Comment by dmd** [comment]
Now I've got this:

```
KeyError: 'blob'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/local/lib/python3.7/site-packages/gkeepapi/node.py(1350)load()
-> self.blob = self.from_json(raw['blob'])
(Pdb) raw
{'kind': 'notes#node', 'id': '1475067403454.685059.727929935', 'serverId': '19Ioh_hI918eEM5ClOop0DI8KmVggtKBWbrh3lgrOvue8WxuGOn-0P71XMBT5Ajnj1_RxrQE', 'parentId': '1475067397817.572021.832690033', 'parentServerId': '1Jkibw8fBmwmyf8LSOdULIBUsnbP4ey-qDmy6tyr_xJWTl-iDKx0XdoOD-lL-MtI_Yw2JCIg', 'type': 'BLOB', 'timestamps': {'kind': 'notes#timestamps', 'created': '2016-09-28T12:56:43.455Z', 'updated': '2018-05-02T14:21:37.740Z', 'deleted': '1970-01-01T00:00:00.000Z'}, 'nodeSettings': {'newListItemPlacement': 'BOTTOM', 'checkedListItemsPolicy': 'GRAVEYARD', 'graveyardState': 'EXPANDED'}, 'annotationsGroup': {'kind': 'notes#annotationsGroup'}}
````

**Comment by dmd** [comment]
I'm not sure how I'd even go about finding a note based on id.

**Comment by mgckind** [comment]
This cli is based heavily on this library, https://github.com/kiwiz/gkeepapi which unfortunately doesn't support Blobs yet,
You can check the `serverId` when you click on a Google Note on the Browser Bar after it is highlighted. 
I'll try to keep debugging this as well to see if I can be more helpful

**Comment by dmd** [comment]
Does that mean I can't use keepcli at all if I have any images anywhere in my Keep?

**Comment by dmd** [comment]
> You can check the serverId when you click on a Google Note on the Browser Bar after it is highlighted.

Hmm, but there doesn't appear to be a way to actually navigate to one, and with many thousands of notes, not sure how I'd get to a specific one.

**Comment by dmd** [comment]
gkeepapi does support blobs, according to its github page.

**Comment by mgckind** [comment]
> gkeepapi does support blobs, according to its github page.

I'd need to update `keepcli` then, I haven't checked in a while

> > You can check the serverId when you click on a Google Note on the Browser Bar after it is highlighted.
> 
> Hmm, but there doesn't appear to be a way to actually navigate to one, and with many thousands of notes, not sure how I'd get to a specific one.

Not that I'm aware of, maybe using `geekpap` directly (and that's a lot of notes :) )


> Does that mean I can't use keepcli at all if I have any images anywhere in my Keep?

Not at the moment, I'll try to find time to update the package to handle blobs and indentation which are on my wish-list
